"""
Generate full-text software engineering resumes from structured synthetic resume records.

This script reads a CSV or Parquet file of structured synthetic resumes, sends each row
to an LLM, and writes a CSV/Parquet with generated resume text.

It supports multiple prompt modes so the capstone can compare full-text resumes with
and without age-proxy leakage.

Example:

python src/llm_resume_generation.py \
  --input data/processed/synthetic_resumes_full.parquet \
  --output data/processed/synthetic_resumes_fulltext_sample.csv \
  --mode without_direct_age_proxies \
  --limit 25

Environment:

export OPENAI_API_KEY="..."
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd
from openai import OpenAI


DEFAULT_MODEL = "gpt-4o-mini"
DEFAULT_PROMPT_VERSION = "v2_schema_aware_fulltext_resume_generation"


# ---------------------------------------------------------------------
# Prompt modes
# ---------------------------------------------------------------------

ALWAYS_EXCLUDE_COLUMNS = {
    # Protected/evaluation fields
    "true_age",
    "age",
    "age_group",

    # Labels/outcomes
    "callback",
    "interview",
    "offer",
    "selected",
    "outcome",
    "target",
    "label",

    # Application preference fields, not resume content
    "salary_expectation_usd",
    "willing_to_relocate",
    "remote_only",

    # Anything generated by this script
    "resume_text",
    "llm_model",
    "prompt_version",
    "generated_at",
    "generation_error",
    "generation_mode",
}


MODE_EXCLUDE_COLUMNS = {
    # Includes common real-world age proxies such as graduation_year,
    # estimated_start_year, years_experience_total, and seniority/title.
    # Still excludes true age, age_group, and labels.
    "with_proxies": set(),

    # Removes explicit date proxies, while preserving experience/seniority fields.
    # This matches your current real-world resume strategy pretty closely.
    "without_direct_age_proxies": {
        "graduation_year",
        "estimated_start_year",
        "salary_expectation_usd",
    },

    # More aggressive attempt to suppress age leakage.
    # Keeps skills and role-relevant facts but removes many age/seniority proxies.
    "minimal_proxy": {
        "graduation_year",
        "estimated_start_year",
        "years_experience_total",
        "years_experience_relevant",
        "num_employers",
        "avg_tenure_years",
        "months_since_last_role",
        "num_gaps_over_6mo",
        "management_years",
        "reports_max",
        "legacy_tech_count",
        "modern_tech_count",
        "leadership_signal_score",
        "stability_score",
        "salary_expectation_usd",
    },
}


SYSTEM_PROMPT = """
You convert structured synthetic resume records into realistic plain-text software engineering resumes.

Rules:
- Preserve only the facts provided in the structured input.
- Do not invent employers, titles, schools, degrees, dates, certifications, awards, metrics, locations, database names, project names, or technologies.
- Only include URLs that are explicitly present in the structured input.
- Do not mention age, age group, protected class, demographics, callback labels, interview labels, offer labels, or fairness labels.
- If a GitHub URL or portfolio URL is present, include it exactly as provided.
- Do not create generic numbered credentials such as "Certification 1", "Certification 2", or "Certification 3".
- If only a certification count is provided, describe it as a count; do not invent certification names.
- Do not mention projects unless project details are provided.
- Do not imply age with phrases like "young professional", "recent graduate", "seasoned veteran", "late-career", or "older candidate".
- Do not add graduation years unless they are present in the structured input.
- Do not add employment dates unless they are present in the structured input.
- If a specific employer name, school name, certification name, project name, URL, or database name is missing, omit it entirely.
- Never use placeholder text such as "[Company Name]", "[School Name]", "[GitHub URL]", "[Certification 1]", "not provided", "unspecified", or similar.
- Never include bracketed placeholders of any kind.
- If highest_degree is "None", omit the Education section rather than writing "Highest Degree: None".
- If the structured input contains counts or scores, translate them into resume-like language without exposing internal score names.
- Keep the resume realistic, concise, professional, and ATS-readable.
- Use plain text only.
- Use sections when supported by the input: Summary, Skills, Experience, Education, Certifications, Projects.
- If a field is missing, omit it rather than filling it in.
- Output only the resume text.
""".strip()


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------

def now_utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def read_dataframe(path: Path) -> pd.DataFrame:
    suffix = path.suffix.lower()

    if suffix == ".csv":
        return pd.read_csv(path)

    if suffix in {".parquet", ".pq"}:
        return pd.read_parquet(path)

    raise ValueError(f"Unsupported input format: {path.suffix}")


def write_dataframe(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    suffix = path.suffix.lower()

    if suffix == ".csv":
        df.to_csv(path, index=False)
        return

    if suffix in {".parquet", ".pq"}:
        df.to_parquet(path, index=False)
        return

    raise ValueError(f"Unsupported output format: {path.suffix}")


def boolish(value: Any) -> bool | None:
    if pd.isna(value):
        return None

    if isinstance(value, bool):
        return value

    text = str(value).strip().lower()
    if text in {"true", "1", "yes", "y"}:
        return True
    if text in {"false", "0", "no", "n"}:
        return False

    return None


def skill_list_from_row(row: pd.Series) -> list[str]:
    skill_map = {
        "skill_python": "Python",
        "skill_java": "Java",
        "skill_javascript": "JavaScript",
        "skill_go": "Go",
        "skill_kubernetes": "Kubernetes",
        "skill_aws": "AWS",
        "skill_gcp": "GCP",
        "skill_azure": "Azure",
        "skill_sql": "SQL",
        "skill_spark": "Spark",
        "skill_terraform": "Terraform",
        "skill_linux": "Linux",
        "skill_ml": "machine learning",
    }

    skills: list[str] = []

    for col, label in skill_map.items():
        if col in row.index and boolish(row[col]) is True:
            skills.append(label)

    return skills

FIRST_NAMES = [
    "Alex", "Jordan", "Taylor", "Morgan", "Casey", "Riley", "Avery", "Quinn",
    "Cameron", "Drew", "Jamie", "Skyler", "Reese", "Rowan", "Emerson",
    "Hayden", "Dakota", "Finley", "Kai", "Logan",
]

LAST_NAMES = [
    "Chen", "Patel", "Garcia", "Nguyen", "Kim", "Brown", "Johnson", "Lee",
    "Martinez", "Singh", "Davis", "Wilson", "Anderson", "Thomas", "Moore",
    "Clark", "Lewis", "Walker", "Hall", "Young",
]


def stable_int(value: Any) -> int:
    """
    Create a deterministic integer from a candidate identifier.
    """
    text = str(value)
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    return int(digest[:12], 16)


def synthetic_person_name(candidate_id: Any) -> dict[str, str]:
    """
    Generate a deterministic synthetic name from candidate_id.

    This avoids introducing real personal data while making generated resumes
    look more realistic.
    """
    seed = stable_int(candidate_id)

    first = FIRST_NAMES[seed % len(FIRST_NAMES)]
    last = LAST_NAMES[(seed // len(FIRST_NAMES)) % len(LAST_NAMES)]

    return {
        "first_name": first,
        "last_name": last,
        "full_name": f"{first} {last}",
    }


def slugify_username_part(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "", value)
    return value


def synthetic_github_url(candidate_id: Any, first_name: str, last_name: str) -> str:
    """
    Create a deterministic fake-but-realistic GitHub URL.

    Uses example.com? No — for GitHub-like screening behavior, use github.com.
    The username is synthetic and deterministic.
    """
    seed = stable_int(candidate_id)
    suffix = 100 + (seed % 900)

    username = (
        f"{slugify_username_part(first_name)}"
        f"{slugify_username_part(last_name)}"
        f"{suffix}"
    )

    return f"https://github.com/{username}"


def synthetic_portfolio_url(candidate_id: Any, first_name: str, last_name: str) -> str:
    """
    Create a deterministic synthetic portfolio URL using example.com.

    example.com is reserved for documentation and avoids accidentally pointing
    to a real personal domain.
    """
    seed = stable_int(candidate_id)
    suffix = 100 + (seed % 900)

    subpath = (
        f"{slugify_username_part(first_name)}-"
        f"{slugify_username_part(last_name)}-"
        f"{suffix}"
    )

    return f"https://example.com/{subpath}"

def compact_record_for_prompt(
    row: pd.Series,
    mode: str,
    id_column: str,
) -> dict[str, Any]:
    """
    Convert a dataframe row into a compact, human-meaningful record for the LLM.

    Instead of dumping every raw column blindly, this groups fields into resume-like
    sections. This makes the model less likely to expose internal synthetic-feature
    names in the generated resume.
    """
    if mode not in MODE_EXCLUDE_COLUMNS:
        valid = ", ".join(sorted(MODE_EXCLUDE_COLUMNS))
        raise ValueError(f"Invalid mode {mode!r}. Valid modes: {valid}")

    exclude_columns = ALWAYS_EXCLUDE_COLUMNS | MODE_EXCLUDE_COLUMNS[mode]

    def has(col: str) -> bool:
        return col in row.index and col not in exclude_columns and not pd.isna(row[col])

    def get(col: str, default: Any = None) -> Any:
        if has(col):
            value = row[col]
            if isinstance(value, str):
                value = value.strip()
                if value == "":
                    return default
            return value
        return default

    record: dict[str, Any] = {}

    candidate_ref = str(row[id_column]) if id_column in row.index else "unknown_candidate"

    # Keep a non-sensitive ID for traceability. The prompt can see it, but it should
    # not be printed in the resume.
    record["candidate_reference"] = candidate_ref

    identity = synthetic_person_name(candidate_ref)
    record["candidate_identity"] = identity
    
    target = {}
    for col in ["application_year", "target_role_family", "target_role_level", "region"]:
        value = get(col)
        if value is not None:
            target[col] = value
    if target:
        record["target_context"] = target

    education = {}
    for col in ["highest_degree", "graduation_year", "school_tier", "gpa_bucket"]:
        value = get(col)
        if value is not None:
            education[col] = value
    if education:
        record["education"] = education

    experience = {}
    for col in [
        "years_experience_total",
        "years_experience_relevant",
        "num_employers",
        "avg_tenure_years",
        "months_since_last_role",
        "num_gaps_over_6mo",
        "most_recent_title",
        "most_recent_company_size",
        "management_years",
        "reports_max",
        "estimated_start_year",
    ]:
        value = get(col)
        if value is not None:
            experience[col] = value
    if experience:
        record["experience_summary"] = experience

    skills = skill_list_from_row(row)
    skill_counts = {}
    for col in [
        "num_skills_listed",
        "num_programming_languages",
        "num_cloud_platforms",
        "num_databases",
        "legacy_tech_count",
        "modern_tech_count",
    ]:
        value = get(col)
        if value is not None:
            skill_counts[col] = value

    if skills or skill_counts:
        record["skills"] = {
            "explicit_skills": skills,
            "skill_counts": skill_counts,
        }

    credentials = {}

    # Keep cert_count only as a count, not as fake named credentials.
    # The prompt below will tell the model not to create "Certification 1", etc.
    for col in [
        "cert_count",
        "has_top_cloud_cert",
        "open_source_mentions",
        "patent_count",
    ]:
        value = get(col)
        if value is not None:
            credentials[col] = value

    # Convert Boolean URL indicators into deterministic synthetic URLs.
    github_present = boolish(get("github_url_present"))
    portfolio_present = boolish(get("portfolio_url_present"))

    if github_present:
        credentials["github_url"] = synthetic_github_url(
            candidate_id=candidate_ref,
            first_name=identity["first_name"],
            last_name=identity["last_name"],
        )

    if portfolio_present:
        credentials["portfolio_url"] = synthetic_portfolio_url(
            candidate_id=candidate_ref,
            first_name=identity["first_name"],
            last_name=identity["last_name"],
        )

    if credentials:
        record["credentials_and_signals"] = credentials

    resume_quality = {}
    for col in [
        "resume_word_count",
        "bullet_count",
        "quantified_impact_count",
        "keyword_match_score",
        "format_clean_score",
    ]:
        value = get(col)
        if value is not None:
            resume_quality[col] = value
    if resume_quality:
        record["resume_quality_guidance"] = resume_quality

    preferences = {}
    for col in [
        "salary_expectation_usd",
        "willing_to_relocate",
        "remote_only",
    ]:
        value = get(col)
        if value is not None:
            preferences[col] = value
    if preferences:
        record["preferences"] = preferences

    derived = {}
    for col in [
        "tech_recency_score",
        "leadership_signal_score",
        "stability_score",
    ]:
        value = get(col)
        if value is not None:
            derived[col] = value
    if derived:
        record["derived_resume_signals"] = derived

    return make_json_safe(record)


def make_json_safe(obj: Any) -> Any:
    """
    Convert numpy/pandas scalar values into JSON-serializable Python objects.
    """
    if isinstance(obj, dict):
        return {str(k): make_json_safe(v) for k, v in obj.items()}

    if isinstance(obj, list):
        return [make_json_safe(v) for v in obj]

    if pd.isna(obj):
        return None

    if hasattr(obj, "item"):
        try:
            return obj.item()
        except Exception:
            pass

    return obj


def build_user_prompt(record: dict[str, Any], mode: str) -> str:
    record_json = json.dumps(record, indent=2, ensure_ascii=False)

    return f"""
Create a full-text software engineering resume from the structured synthetic resume record below.

Generation mode:
{mode}

Structured record:
{record_json}

Additional constraints:
- Preserve the factual content of the structured record.
- Do not add new facts.
- Do not mention the generation mode.
- Do not mention age, age group, callback, interview, offer, target label, protected fields, or fairness analysis.
- Do not output internal field names like keyword_match_score, format_clean_score, tech_recency_score, or leadership_signal_score.
- Do not use bracketed placeholders.
- Do not write "unspecified", "not provided", or "details not provided".
- If details are missing, leave them out.
- If highest_degree is "None", omit the Education section.
- Translate structured signals into natural resume wording.
- Include GitHub or portfolio URLs only when actual URL fields are present.
- If GitHub or portfolio URLs are present, copy them exactly.
- Do not create generic numbered credentials such as "Certification 1", "Certification 2", or "Certification 3".
- If only a certification count is provided, mention the count only; do not invent certification names.
- Do not mention projects unless project details are present.
- Output only the resume text.
""".strip()


def generate_resume_text(
    client: OpenAI,
    record: dict[str, Any],
    mode: str,
    model: str,
    temperature: float = 0.2,
    max_retries: int = 3,
    retry_sleep_seconds: float = 3.0,
) -> str:
    user_prompt = build_user_prompt(record, mode=mode)

    last_error: Exception | None = None

    for attempt in range(1, max_retries + 1):
        try:
            response = client.chat.completions.create(
                model=model,
                temperature=temperature,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
            )

            content = response.choices[0].message.content
            if content is None or not content.strip():
                raise ValueError("Model returned empty content.")

            return content.strip()

        except Exception as exc:
            last_error = exc
            print(f"Attempt {attempt}/{max_retries} failed: {exc}")

            if attempt < max_retries:
                time.sleep(retry_sleep_seconds * attempt)

    raise RuntimeError(f"Failed after {max_retries} attempts.") from last_error


def generate_fulltext_resumes(
    input_path: Path,
    output_path: Path,
    mode: str,
    model: str,
    api_key: str | None,
    id_column: str,
    limit: int | None,
    sleep_seconds: float,
    save_every: int,
    overwrite: bool,
) -> pd.DataFrame:
    if mode not in MODE_EXCLUDE_COLUMNS:
        valid = ", ".join(sorted(MODE_EXCLUDE_COLUMNS))
        raise ValueError(f"Invalid mode {mode!r}. Valid modes: {valid}")

    input_df = read_dataframe(input_path)

    if limit is not None:
        input_df = input_df.head(limit).copy()

    if id_column not in input_df.columns:
        print(f"Warning: id_column {id_column!r} not found. Creating it from row index.")
        input_df[id_column] = [f"row_{i:06d}" for i in range(len(input_df))]

    # If output exists, resume where we left off.
    if output_path.exists() and not overwrite:
        output_df = read_dataframe(output_path)

        required_cols = {id_column, "generation_mode", "resume_text"}
        if required_cols.issubset(output_df.columns):
            prior = output_df[
                output_df["generation_mode"].astype(str) == mode
            ][
                [
                    id_column,
                    "generation_mode",
                    "resume_text",
                    "llm_model",
                    "prompt_version",
                    "generated_at",
                    "generation_error",
                ]
            ]

            output_df = input_df.merge(
                prior,
                on=id_column,
                how="left",
            )
        else:
            output_df = input_df.copy()
    else:
        output_df = input_df.copy()

    text_output_cols = [
        "generation_mode",
        "resume_text",
        "llm_model",
        "prompt_version",
        "generated_at",
        "generation_error",
    ]

    for col in text_output_cols:
        if col not in output_df.columns:
            output_df[col] = pd.Series([pd.NA] * len(output_df), dtype="string")
        else:
            output_df[col] = output_df[col].astype("string")

    client = OpenAI(api_key=api_key or os.environ.get("OPENAI_API_KEY"))

    total = len(output_df)

    for idx, row in output_df.iterrows():
        existing_text = row.get("resume_text")

        if not overwrite and isinstance(existing_text, str) and existing_text.strip():
            continue

        candidate_id = row[id_column]
        print(f"Generating {idx + 1}/{total} | {id_column}={candidate_id} | mode={mode}")

        try:
            record = compact_record_for_prompt(
                row=row,
                mode=mode,
                id_column=id_column,
            )

            resume_text = generate_resume_text(
                client=client,
                record=record,
                mode=mode,
                model=model,
            )

            output_df.at[idx, "generation_mode"] = mode
            output_df.at[idx, "resume_text"] = resume_text
            output_df.at[idx, "llm_model"] = model
            output_df.at[idx, "prompt_version"] = DEFAULT_PROMPT_VERSION
            output_df.at[idx, "generated_at"] = now_utc_iso()
            output_df.at[idx, "generation_error"] = None

        except Exception as exc:
            output_df.at[idx, "generation_mode"] = mode
            output_df.at[idx, "generation_error"] = str(exc)
            print(f"Failed {id_column}={candidate_id}: {exc}")

        if (idx + 1) % save_every == 0:
            write_dataframe(output_df, output_path)
            print(f"Saved checkpoint to {output_path}")

        time.sleep(sleep_seconds)

    write_dataframe(output_df, output_path)
    print(f"Done. Wrote {output_path}")

    return output_df


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate full-text resumes from structured synthetic resume records."
    )

    parser.add_argument(
        "--input",
        required=True,
        help="Path to input CSV or Parquet file.",
    )

    parser.add_argument(
        "--output",
        required=True,
        help="Path to output CSV or Parquet file.",
    )

    parser.add_argument(
        "--mode",
        default="without_direct_age_proxies",
        choices=sorted(MODE_EXCLUDE_COLUMNS.keys()),
        help="Prompt mode controlling which age-proxy fields are visible to the LLM.",
    )

    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"LLM model name. Default: {DEFAULT_MODEL}",
    )

    parser.add_argument(
        "--api-key",
        default=None,
        help="API key. Prefer OPENAI_API_KEY environment variable.",
    )

    parser.add_argument(
        "--id-column",
        default="candidate_id",
        help="Unique row identifier column. Default: candidate_id",
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Generate only first N rows. Useful for testing.",
    )

    parser.add_argument(
        "--sleep-seconds",
        type=float,
        default=0.2,
        help="Delay between API calls.",
    )

    parser.add_argument(
        "--save-every",
        type=int,
        default=10,
        help="Checkpoint every N rows.",
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Regenerate rows even if resume_text already exists.",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    generate_fulltext_resumes(
        input_path=Path(args.input),
        output_path=Path(args.output),
        mode=args.mode,
        model=args.model,
        api_key=args.api_key,
        id_column=args.id_column,
        limit=args.limit,
        sleep_seconds=args.sleep_seconds,
        save_every=args.save_every,
        overwrite=args.overwrite,
    )


if __name__ == "__main__":
    main()